apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-07-25T03:10:12Z"
  generateName: ebs-disk-csi-cds-node-
  labels:
    app: ebs-disk-csi-cds-node
    controller-revision-hash: bff76ff45
    pod-template-generation: "1"
  name: ebs-disk-csi-cds-node-m2gdh
  namespace: kube-system
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: DaemonSet
      name: ebs-disk-csi-cds-node
      uid: ba953fb3-5ae4-40cc-8293-f7ad32b99637
  resourceVersion: "880475"
  uid: d0d40d86-df7b-4099-8c4a-a43d969c8cc3
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchFields:
              - key: metadata.name
                operator: In
                values:
                  - ins-fufskqstqn4ea0g8
  containers:
    - args:
        - --endpoint=$(CSI_ENDPOINT)
        - --v=5
        - --driver=ebs-disk.csi.cds.net
      env:
        - name: CSI_ENDPOINT
          value: unix://var/lib/kubelet/plugins/ebs-disk.csi.cds.net/csi.sock
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: access_key_id
              name: cck-secrets
        - name: ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: access_key_secret
              name: cck-secrets
        - name: CDS_OVERSEA
          valueFrom:
            configMapKeyRef:
              key: oversea
              name: cds-properties
        - name: API_HOST
          value: http://api.capitalonline.net
      image: harbor-dev.yun-paas.com/test/cds-csi-driver:v2.1.6
      imagePullPolicy: Always
      name: ebs-disk-csi-node-server
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        capabilities:
          add:
            - SYS_ADMIN
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/lib/kubelet/
          mountPropagation: Bidirectional
          name: kubelet-dir
        - mountPath: /var/log/
          name: host-log
        - mountPath: /host/etc
          name: etc
        - mountPath: /dev
          name: host-dev
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-xk768
          readOnly: true
    - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
      env:
        - name: ADDRESS
          value: /var/lib/kubelet/plugins/ebs-disk.csi.cds.net/csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: /var/lib/kubelet/plugins/ebs-disk.csi.cds.net/csi.sock
      image: registry-bj.capitalonline.net/cck/csi-node-driver-registrar:v1.2.0
      imagePullPolicy: Always
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - -c
              - rm -rf /registration/ebs-disk.csi.cds.net /registration/ebs-disk.csi.cds.net-reg.sock
      name: ebs-disk-driver-registrar
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/lib/kubelet/
          name: kubelet-dir
        - mountPath: /registration/
          name: registration-dir
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-xk768
          readOnly: true
    - args:
        - --csi-address=/var/lib/kubelet/plugins/ebs-disk.csi.cds.net/csi.sock
        - --health-port=9812
      image: registry-bj.capitalonline.net/cck/csi-livenessprobe:v2.0.0
      imagePullPolicy: IfNotPresent
      name: ebs-disk-liveness-probe
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/lib/kubelet/
          name: kubelet-dir
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-xk768
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  hostPID: true
  nodeName: ins-fufskqstqn4ea0g8
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: ebs-disk-cds-csi-sa
  serviceAccountName: ebs-disk-cds-csi-sa
  terminationGracePeriodSeconds: 30
  tolerations:
    - operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/disk-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/pid-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/unschedulable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/network-unavailable
      operator: Exists
  volumes:
    - emptyDir: {}
      name: socket-dir
    - hostPath:
        path: /var/lib/kubelet
        type: Directory
      name: kubelet-dir
    - hostPath:
        path: /var/lib/kubelet/plugins_registry
        type: DirectoryOrCreate
      name: registration-dir
    - hostPath:
        path: /var/log/
        type: ""
      name: host-log
    - hostPath:
        path: /etc
        type: ""
      name: etc
    - hostPath:
        path: /dev
        type: ""
      name: host-dev
    - name: kube-api-access-xk768
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-07-25T03:10:12Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-07-25T03:10:14Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-07-25T03:10:14Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-07-25T03:10:12Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: containerd://21b9632587137493199eb063adc95bd8a8bd084ab9b797d6ff496287162bda03
      image: harbor-dev.yun-paas.com/test/cds-csi-driver:v2.1.6
      imageID: harbor-dev.yun-paas.com/test/cds-csi-driver@sha256:6f06a8abc40d0aeeb415ffece2573ae15b5220416f6bccf7846122a39620501b
      lastState: {}
      name: ebs-disk-csi-node-server
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-07-25T03:10:13Z"
    - containerID: containerd://f23eac098e89f9475eb76f062f1cca2dc6ed993cc7875896635b1482ef5f71cb
      image: registry-bj.capitalonline.net/cck/csi-node-driver-registrar:v1.2.0
      imageID: registry-bj.capitalonline.net/cck/csi-node-driver-registrar@sha256:273175c272162d480d06849e09e6e3cdb0245239e3a82df6630df3bc059c6571
      lastState: {}
      name: ebs-disk-driver-registrar
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-07-25T03:10:14Z"
    - containerID: containerd://47e9c9f7efb04ea981e2b103554f00c9ace563d3f76cfa0f4812293ada81d294
      image: registry-bj.capitalonline.net/cck/csi-livenessprobe:v2.0.0
      imageID: registry-bj.capitalonline.net/cck/csi-livenessprobe@sha256:ac12fcab5bd2550d580a83b531ccea0f446ae16e5c9ed29e9c676e5ed9f4e264
      lastState: {}
      name: ebs-disk-liveness-probe
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-07-25T03:10:14Z"
  hostIP: 10.1.6.7
  phase: Running
  podIP: 10.1.6.7
  podIPs:
    - ip: 10.1.6.7
  qosClass: BestEffort
  startTime: "2024-07-25T03:10:12Z"