---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - eci.eci.cds
  resources:
  - podrecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eci.eci.cds
  resources:
  - podrecords/finalizers
  verbs:
  - update
- apiGroups:
  - eci.eci.cds
  resources:
  - podrecords/status
  verbs:
  - get
  - patch
  - update
