apiVersion: v1
kind: ConfigMap
metadata:
  name: eci-config
  namespace: kube-system
data:
  exclude: '[
    {
        "kind": "Deployment",
        "name": "coredns",
        "namespace": "kube-system"
    },
    {
        "kind": "DaemonSet",
        "name": "kube-flannel-ds",
        "namespace": "kube-flannel"
    },
    {
        "kind": "Node",
        "name": "kube-apiserver",
        "namespace": "kube-system"
    },
    {
        "kind": "DaemonSet",
        "name": "kube-proxy",
        "namespace": "kube-system"
    },
    {
        "kind": "DaemonSet",
        "name": "ebs-disk-csi-cds-node",
        "namespace": "kube-system"
    },
    {
        "kind": "StatefulSet",
        "name": "ebs-disk-csi-cds-controller",
        "namespace": "kube-system"
    }
]'