apiVersion: batch/v1
kind: CronJob
metadata:
  name: podrecord-service-healthcheck
  namespace: kube-system
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: podrecord-service-healthcheck
              image: harbor-dev.yun-paas.com/test/alpine:3.14
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - result=$(curl http://podrecord-service/healthz 2>&1) && echo $result | grep ok || curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=867a4e99-f723-492e-b312-8f25cc3d1eb3' -H 'Content-Type:application/json' -X POST -d "{\"msgtype\":\"markdown\",\"markdown\":{\"content\":\"pod计费组件告警<font color=\\\"warning\\\">健康检查失败</font>，请相关同事注意。\\n> 客户ID:<font color=\\\"comment\\\"> $CUSTOMER_ID</font>\\n> 集群ID:<font color=\\\"comment\\\"> $CLUSTER_ID</font>\\n> 报错信息:<font color=\\\"comment\\\"> $result</font>\\n报错时间:<font color=\\\"comment\\\"> $(date)</font>\"}}"; exit 0
              env:
                - name: CUSTOMER_ID
                  value: ""
                - name: CLUSTER_ID
                  value: ""
          restartPolicy: OnFailure